### ISSUE TITLE
Reports on Forum Dashboard differ from GA

### ISSUE THREAD

**Issue by ficofer** [julianlam/nodebb-plugin-google-analytics#24]
The issue we are having with this use case is that the Unique visitors and users shown in the NodeBB forum dashboard differs from the GA dashboard, is a way this can be resolved? Or check? Any cache needed to be clean?

I am not sure If I am the only users experiencing this.

**Comment by julianlam** [comment]
Typically, the data doesn't match up completely due to a variety of reasons, but reporting error usually isn't one of those (at least, I hope not!).

GA tends to filter out bots, whereas NodeBB would count them just like any other user.
The GA plugin also doesn't count users who have javascript disabled.

... among other reasons, of course, too many to enumerate.
